import { Property } from "@/types/property";

export const mockProperties: Property[] = [
  {
    _id: "1",
    owner: "1",
    name: "Test Property 1",
    type: "House",
    description: "desc",
    location: { street: "", city: "", state: "", zipcode: "" },
    beds: 1,
    baths: 1,
    square_feet: 100,
    amenities: [],
    rates: {},
    seller_info: { name: "", email: "", phone: "" },
    images: [],
    is_featured: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "2",
    owner: "2",
    name: "Test Property 2",
    type: "Apartment",
    description: "desc",
    location: { street: "", city: "", state: "", zipcode: "" },
    beds: 2,
    baths: 1,
    square_feet: 200,
    amenities: [],
    rates: {},
    seller_info: { name: "", email: "", phone: "" },
    images: [],
    is_featured: false,
    createdAt: "",
    updatedAt: "",
  },
  {
    _id: "3",
    owner: "3",
    name: "Test Property 3",
    type: "Condo",
    description: "desc",
    location: { street: "", city: "", state: "", zipcode: "" },
    beds: 3,
    baths: 2,
    square_feet: 300,
    amenities: [],
    rates: {},
    seller_info: { name: "", email: "", phone: "" },
    images: [],
    is_featured: true,
    createdAt: "",
    updatedAt: "",
  },
];

export const mockProperty: Property = {
  _id: "mock-001",
  owner: "mock-owner-88",
  name: "Aurora Skyline Apartment",
  type: "Apartment",
  description:
    "A modern apartment perched above the city lights, featuring panoramic views, luxury finishes, and a private rooftop terrace.",
  location: {
    street: "777 Aurora Boulevard",
    city: "Metropolis",
    state: "NY",
    zipcode: "10199",
  },
  beds: 3,
  baths: 2,
  square_feet: 2100,
  amenities: [
    "Panoramic Views",
    "Private Rooftop Terrace",
    "Smart Home System",
    "Saltwater Jacuzzi",
    "Floor-to-Ceiling Windows",
    "Heated Marble Floors",
    "Private Elevator Access",
  ],
  rates: {
    nightly: 650,
    weekly: 3500,
    monthly: 12000,
  },
  seller_info: {
    name: "Avery Luna",
    email: "avery.luna@luxestays.com",
    phone: "800-555-9090",
  },
  images: ["aurora-rooftop.jpg", "aurora-livingroom.jpg", "aurora-bedroom.jpg"],
  is_featured: true,
  createdAt: "2025-01-15T12:00:00.000Z",
  updatedAt: "2025-01-15T12:00:00.000Z",
};
